# Generated by Django 2.0 on 2019-12-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20191223_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='tipe',
            field=models.TextField(choices=[('primary', 'Primary'), ('congress', 'Congress')], default='primary', verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voting',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
