# Generated by Django 2.0 on 2019-12-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20191227_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='political_party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.PoliticalParty'),
            preserve_default=False,
        ),
    ]
