# Generated by Django 2.0 on 2019-12-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_voting_political_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.TextField(choices=[('admin', 'admin'), ('user1', 'user1')]),
        ),
    ]
