# Generated by Django 2.0 on 2019-12-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20191227_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.TextField(help_text='You must put a valid username'),
        ),
    ]
