# Generated by Django 2.0 on 2020-01-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20191230_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='political_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.PoliticalParty'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='tipe',
            field=models.TextField(choices=[('PP', 'Presidential primaries'), ('SP', 'Senate primaries')], verbose_name='Type'),
        ),
    ]
