# Generated by Django 2.0 on 2020-01-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20200102_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalparty',
            name='president',
            field=models.CharField(blank=True, help_text='You must do a primary presidential voting if you want select a new president', max_length=151, null=True),
        ),
    ]
