# Generated by Django 2.0 on 2020-01-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_auto_20200105_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='tipe',
            field=models.TextField(choices=[('PP', 'Presidential primaries'), ('SP', 'Senate primaries'), ('S', 'Senate'), ('P', 'Presidential'), ('O', 'Other')], verbose_name='Type'),
        ),
    ]
