# Generated by Django 2.0 on 2020-01-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_voting_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='province',
            field=models.CharField(blank=True, choices=[('S', 'Sevillistán'), ('H', 'Huelvistán'), ('C', 'Cadistán')], max_length=1, null=True, verbose_name='Province'),
        ),
    ]
