# Generated by Django 2.0 on 2020-01-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_auto_20200105_2000'),
        ('voting', '0014_auto_20200108_1013'),
    ]

    operations = [
    ]
