# Generated by Django 2.0 on 2020-01-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employment',
            field=models.CharField(blank=True, choices=[('M', 'Militant'), ('B', 'Baron'), ('S', 'Senator'), ('P', 'President')], max_length=1, null=True, verbose_name='Employment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(choices=[('S', 'Sevillistán'), ('H', 'Huelvistán'), ('C', 'Cadistán')], max_length=1, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='related_political_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PoliticalParty', to='voting.PoliticalParty'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Sex'),
        ),
    ]
